#pragma once
#define _USE_MATH_DEFINES

#include <vector>
#include <filesystem>
#include <fstream>
#include <string>  
#include <memory>
#include <unordered_map>
#include <unordered_set>
#include <chrono>
#include <queue>
#include <algorithm>
#include <thread>
#include <ctime>
#include <set>
#include <array>
#include "AdditionalMath.h"
#include <optional>
#include <cstring> 
#include <type_traits>