set(ANOMALY_ENGINE_INCLUDED ON CACHE BOOL "")
if(ANOMALY_ENGINE_INCLUDED)
add_compile_definitions(ANOMALY_ENGINE_INCLUDED)
endif()

set(USER_SCRIPTS_REGISTER_INCLUDED ON CACHE BOOL "")
if(USER_SCRIPTS_REGISTER_INCLUDED)
add_compile_definitions(USER_SCRIPTS_REGISTER_INCLUDED)
endif()

